from __future__ import annotations

import os
from typing import Any

import httpx
import streamlit as st
from shared.logging_config import logger

API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")

def _fetch_weekly_report() -> dict[str, Any]:
    try:
        response = httpx.get(f"{API_BASE_URL}/weekly_report", timeout=100.0)
        response.raise_for_status()
        payload = response.json()
        return payload if isinstance(payload, dict) else {}
    except Exception as exc:
        logger.warning("Unable to fetch weekly report from backend: %s", exc)
        return {}
    
def render_reporting_page() -> None:
    st.title("📊 Reporting Page")
    st.write("View the weekly report generated by the backend.")
    
    report = _fetch_weekly_report()
    
    if report:
        st.subheader("Weekly Report")
        st.write(f"Total Customers: {report.get('total_customers', 'N/A')}")
        st.write(f"Total Complaints: {report.get('total_complaints', 'N/A')}")
        st.write(f"Open Complaints: {report.get('open_complaints', 'N/A')}")
        st.write(f"Closed Complaints: {report.get('closed_complaints', 'N/A')}")
        st.write(f"Total Tasks: {report.get('total_tasks', 'N/A')}")
    else:
        st.warning("Unable to fetch the weekly report. Please try again later.")

if __name__ == "__main__":
    st.set_page_config(page_title="Reporting Agent", page_icon="🏦", layout="wide")
    render_reporting_page()
    st.write("This page fetches the weekly report from the backend and displays it in a user-friendly format.")
    